name: Todofy Build

on:
  push:
    branches:
      - main
    paths:
      - "self_host/packages/todofy/**"
      - "scripts/build_docker_image.sh"
      - ".github/workflows/todofy-build.yml"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build docker image
        run: |
          bash scripts/build_docker_image.sh latest

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/todofy:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-llm:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-todo:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-database:latest
