name: Todofy Build

on:
  push:
    branches:
      - main
    paths:
      - "self_host/packages/todofy/**"
      - "scripts/build_docker_image.sh"
      - ".github/workflows/todofy-build.yml"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

        # Install protoc
      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      # Install protoc-gen-go and protoc-gen-go-grpc
      - name: Install Protoc Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          # Add the go bin path to PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.13.0
        with:
          bazelisk-cache: true
          # disk-cache: ${{ github.workflow }}
          repository-cache: false

      - name: Build docker image
        run: |
          bash scripts/build_docker_image.sh latest

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/todofy:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-llm:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-todo:latest
          docker push ghcr.io/${{ github.repository_owner }}/todofy-database:latest
